version: "3.9"  # optional since v1.27.0
services:
  killer:
    container_name: upml_killerbot
    image: upml_killerimage
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
      - db_files:/app/src/database/db_files
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1

volumes:
  db_files:
